/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinseonkim_photocloud_imageService_ImageCompressing */

#ifndef _Included_com_jinseonkim_photocloud_imageService_ImageCompressing
#define _Included_com_jinseonkim_photocloud_imageService_ImageCompressing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jinseonkim_photocloud_imageService_ImageCompressing
 * Method:    compressedImage
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jinseonkim_photocloud_imageService_ImageCompressing_compressedImage
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
